# Define la imagen globalmente
default:
  image: python:latest

variables:
  DJANGO_SETTINGS_MODULE: "djangoreactcrud.settings" # Replace with your project's settings module
  DATABASE_URL: "postgres://postgres:postgres@10.0.0.82:5432/djangoReactCrud"   # Example for SQLite, change for other DBs
  DOCKER_HOST: tcp://10.0.0.77:2375
  DOCKER_DRIVER: "overlay2"

cache:
  paths:
    - ~/.cache/pip


stages:
  - lint
  - test
  - build
  - deploy


lint_job:
  stage: lint
  script:
    - pip install flake8
    - flake8 --extend-ignore=E302,E303,E111,E117,E251,E121,E123,E126,E225,E226,E24,E231,E704,F401,F403,F405,F841,W503,W504,W291,W292,W293 --max-line-length 300 .
  allow_failure: true


test_job:
  stage: test
  script:
    - pip install -r requirements.txt
    - coverage run manage.py test
    - coverage report
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build_job:
  stage: build
  script:
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py makesuperuser
  artifacts:
    paths:
      - static/

deploy_job:
  stage: deploy
  image: docker:latest
  services: 
    - docker:dind
  before_script:
    - docker --version || echo 'Docker CLI not found'
  script:
    - echo "Deploying to production..."
    - docker compose build --no-cache
    - docker compose up -d
  only:
    - main

