# Generated by Django 5.1.5 on 2025-04-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Characteristic', 'verbose_name_plural': 'Characteristics'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countrys'},
        ),
        migrations.AlterModelOptions(
            name='footballclub',
            options={'verbose_name': 'FootballClub', 'verbose_name_plural': 'FootballClubs'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
