# Generated by Django 5.1.5 on 2025-04-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_characteristic_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
    ]
