"""
Django settings for djangoreactcrud project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
from dj_database_url import parse
from import_export.formats.base_formats import CSV, XLSX
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lpru5jqsh4*rn_p2@jz246-@(=#i8z82=f0=kh769)5**uk-vj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
    'rest_framework',
    'import_export',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# CORS_ALLOW_METHODS = [
#     "GET",
#     "POST",
#     "PUT",
#     "DELETE",
#     "OPTIONS",
#     "PATCH",
# ]

# CORS_ALLOW_HEADERS = [
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
# ]


# CORS_ALLOWED_ORIGINS = [
#     'http://10.0.0.77',
#     'https://10.0.0.77',
#     'http://10.0.0.77:5173',
#     'https://10.0.0.77:5173',
#     'http://localhost:5173',    
# ]

# CORS_ORIGIN_ALLOW_ALL = False

# CORS_ALLOW_ALL_ORIGINS = True

CSRF_COOKIE_NAME = 'XSRF-TOKEN'
CSRF_HEADER_NAME = 'HTTP_X_XSRF_TOKEN'
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    'http://10.0.0.77'
]

# CORS_ORIGIN_WHITELIST = [
#     'http://10.0.0.77',
#     'https://10.0.0.77',
#     'http://10.0.0.77:5173',
#     'https://10.0.0.77:5173',
#     'http://localhost:5173',   

# ]

# CORS_ALLOW_METHODS = [
#     'GET',
#     'POST',
#     'PUT',
#     'DELETE',
#     'OPTIONS',
#     'PATCH',
# ]

# CORS_ALLOW_HEADERS = [
#     'Content-Type',
#     'Authorization',
# ]

# CORS_ALLOW_HEADERS = default_headers + (
#     "cache-control",
#     "custom-headers",
#     "Sec-Ch-Ua-Platform",
#     "Sec-Ch-Ua-Mobile",
#     "Sec-Ch-Ua",
#     "Referer",
#     "Content-Type",
#     "Authorization",
# )

# CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = [
    'http://localhost:5173',
    'http://10.0.0.77:5173',
]

# CORS_ORIGIN_ALLOW_ALL = True

# CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOW_CREDENTIALS = True



# CORS_ALLOW_HEADERS = default_headers + (
#     'Access-Control-Allow-Origin',
# )

# CSRF_TRUSTED_ORIGINS = [
#     'http://10.0.0.77:1337',
#     'https://10.0.0.77:1337',
#     'http://localhost:8000',
#     'http://localhost:1337',
#     'https://localhost:8000',
#     'https://localhost:1337',
#     'http://127.0.0.1:8000',
#     'http://127.0.0.1:1337',
#     'https://127.0.0.1:8000',
#     'https://127.0.0.1:1337',

# ]
# CSRF_ALLOWED_ORIGINS = [
#     'http://10.0.0.77:1337',
#     'https://10.0.0.77:1337', 
# ]
# CORS_ORIGINS_WHITELIST = [
#     'http://10.0.0.77:1337',
#     'https://10.0.0.77:1337', 
# ]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ROOT_URLCONF = 'djangoreactcrud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoreactcrud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'djangoReactCrud',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': config(
        'DATABASE_URL',
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        cast=parse
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/accounts/profile/'

LOGIN_URL = '/accounts/profile/'

LOGOUT_REDIRECT_URL = '/'


IMPORT_FORMATS = [CSV]

EXPORT_FORMATS = [CSV]

# APPEND_SLASH=False

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ]
}